language: python

python:
  - '3.5'
  - '3.6'

before_install:
  - sudo apt-get update

install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

script: make test

after_success: coveralls

notifications:
  email:
    recipients:
      - allen@pingthings.io
    on_success: change
    on_failure: always
