name: build
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:

  test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tests
        run: |
          make test

