name: build
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:

  test-suite:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install flake8 pytest
        pip install -r requirements.txt
        pip install -r tests/requirements.txt
    - name: Test with pytest
      run: |
        pytest